pipeline:
  build:
    image: ruby:2.4.3
    commands:
      - apt-get update && apt-get install -y nodejs
      - bundle install --path=.bundle
      - bundle exec rake db:migrate


services:
  db_host:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    commands:
      - echo 'create database dev_db;' | mysql -u root -h 127.0.0.1
