pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.bundle
    volumes:
      - /tmp/cache:/cache
  build:
    image: ruby:2.4.3
    commands:
      - apt-get update && apt-get install -y nodejs
      - bundle install --path=.bundle
      - bundle exec rake db:migrate
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.bundle
    volumes:
      - /tmp/cache:/cache


services:
  db_host:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dev_db
