default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password:
  host: <%= ENV.fetch('DB_HOST', 'db_host') %>
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: dev_db

production:
  <<: *default
  database: prod_db
